-- require("neotest").setup({
--   adapters = {
--     require("neotest-python")({
--         runner = "nosetest",
--         python = "C:/Users/akepka/.virtualenvs/bfd/Scripts/python.exe",
--         args = {
--             "--traverse-namespace",
--             -- "--with-neotest"
--         },
--     })
--   }
-- })
